Разметка страницы index.html
htmlacademy-htmlcss/1404645-sedona-34 pull request #2
Opened 2022-05-31 14:56 UTC by gr-sv

2022-05-31 18:11 UTC, Pakistanka requested changes

2022-05-31 18:11 UTC, Pakistanka commented on .editorconfig
> +indent_size = 4
А зачем был изменен .editorconfig?

2022-05-31 18:11 UTC, Pakistanka commented on index.html
> +					  <a class="navigation-link navigation-link-current">Главная</a>
Потерян атрибут href

2022-05-31 18:11 UTC, Pakistanka commented on index.html
> +					  <span class="visually-hidden">Ваш e-mail</span>
Не совсем понимаю, зачем дополнительная обертка в виде span? 
Она избыточна

2022-05-31 18:11 UTC, Pakistanka commented on index.html
> +						  <span class="visually-hidden">ВКонтакте</span>
Тег span избыточен

2022-05-31 18:11 UTC, Pakistanka commented on index.html
> +						  <span class="visually-hidden">Twitter</span>
Тег span избыточен

2022-05-31 18:11 UTC, Pakistanka commented on index.html
> +						  <span class="visually-hidden">YouTube</span>
Тег span избыточен

2022-06-01 11:14 UTC, gr-sv commented on index.html
> +					  <a class="navigation-link navigation-link-current">Главная</a>
Ок.

2022-06-01 11:16 UTC, gr-sv commented on index.html
> +					  <span class="visually-hidden">Ваш e-mail</span>
Делал по аналогии с демонстрацией в разделе 2. Добавить class="visually-hidden" тегу <label>?

2022-06-01 11:21 UTC, gr-sv commented on .editorconfig
> +indent_size = 4
Разбирался с настройками редактора кода и с этим файлом, в том числе.  Если этот файл трогать не надо, то верну как было.

2022-06-03 13:58 UTC, merged